#%RAML 1.0 NamedExample
example:
  {
    "message": ="Mouritech Private Limited,Huda Techno Enclave,Survey No. 64,4th Floor,SBR Surya Pearl Sector III,IT Park,Madhapur,Hitech City Main Rd,Phase 2,Opposite to Mindspace,Top of Karachi Bakery and Burger king,HITEC City,Hyderabad,Telangana 500081"
  }
  