#%RAML 1.0
title: poc14
/poc14:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"20200909080000"
              }
