#%RAML 1.0
title: Poc2-proc
/flights:
  get:
    queryParameters:
      price:
        type: number
        required: true
    responses:
      200:
        body:
          application/json:
            example: !include example/example.raml
              